### ISSUE TITLE
Updating PHPBrew Builds

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#13]
@AnoopAlias I finally have the PHPBrew 5.5.20 build working with all the correct modules and configuration to work with my main sites.

However, I'd like to update to a newer version of 5.5.X with the same modules compiled in. How can I do this?

Thanks!

**Comment by AnoopAlias** [comment]
You basically have to build the newer version with the same options as you did in the previous build . note that phpbrew is a multi version installer .So there is no concept like upgrade php5.5.x to a newer one .You just build the new one alongside the old and delete the old one if its not required . Each version will be installed into its own folder .

Also read : https://github.com/phpbrew/phpbrew/wiki/Cookbook

**Comment by brianjking** [comment]
@AnoopAlias -- I'm a bit confused and hope you can help! Your SSH key is still in my hosts file, just FYI.

```
[root@lw ~]# phpbrew update
===> Fetching release list...
[==================================================================] 184.00/184.00B 100%
Redirecting to https://secure.php.net/releases/index.php?json&version=5&max=100
5.6: 12 releases
5.5: 28 releases
5.4: 44 releases
5.3: 16 releases
===> Done
[root@lw ~]# phpbrew known
5.6: 5.6.11, 5.6.10, 5.6.9, 5.6.8, 5.6.7, 5.6.6, 5.6.5, 5.6.4 ...
5.5: 5.5.27, 5.5.26, 5.5.25, 5.5.24, 5.5.23, 5.5.22, 5.5.21, 5.5.20 ...
5.4: 5.4.43, 5.4.42, 5.4.41, 5.4.40, 5.4.39, 5.4.38, 5.4.37, 5.4.36 ...
5.3: 5.3.29, 5.3.28, 5.3.27, 5.3.26, 5.3.25, 5.3.24, 5.3.23, 5.3.22 ...
You can run `phpbrew update` to get a newer release list.
[root@lw ~]# phpbrew install --like php-5.5.20 --as php-5.5.27
GetOptionKit\Exception\InvalidOptionException: Invalid option: --as
Trace:

    0) GetOptionKit\ContinuousOptionParser->parse(['/usr/bin/phpbrew', 'install', '--like', 'php-5.5.20', '--as', 'php-5.5.27'])
    1) GetOptionKit\ContinuousOptionParser->continueParse()
    2) CLIFramework\Application->run(['/usr/bin/phpbrew', 'install', '--like', 'php-5.5.20', '--as', 'php-5.5.27'])
    3) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'install', '--like', 'php-5.5.20', '--as', 'php-5.5.27'])
    4) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')

[root@lw ~]# phpbrew install phpbrew 5.5.27
Exception: Version phpbrew not found.
Trace:

    0) PhpBrew\Command\InstallCommand->execute('phpbrew', '5.5.27')
    1) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['phpbrew', '5.5.27'])
    2) CLIFramework\CommandBase->executeWrapper(['phpbrew', '5.5.27'])
    3) CLIFramework\Application->run(['/usr/bin/phpbrew', 'install', 'phpbrew', '5.5.27'])
    4) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'install', 'phpbrew', '5.5.27'])
    5) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')
```

**Comment by brianjking** [comment]
@AnoopAlias Please help!

**Comment by AnoopAlias** [comment]
@brianjking .phpbrew is a bit cumbersome as we have to apply all the options again to compile the new version . One easy way to apply the current cPanel config is

phpbrew install 5.x.x +fpm -- CONFIGOPTIONS

Where CONFIGOPTIONS can ge got from the command 

php-config --configure-options 


Note that you must delete the "--prefix=/usr/local" from the above manually as otherwise the install will overwrite system php.

To get rid of all these hassles you can use the PHP installed from remi repo using command
/opt/nDeploy/scripts/easy_php_setup.sh

This will install 3 versions of PHP and always keep it updated using yum .

Again phpbrew recompile is not an nDeploy bug. So this issue is  a wontFix .You can avail our tech support and have one of our admins compile phprew new version at hourly support rates if you wish
