### ISSUE TITLE
MPM_Event versus MPM_Worker with EasyApache4

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#28]
By default all of the EasyApache4 builds are configured with MPM_Worker, is there a reason the REMI builds or phpbrew builds always suggest being used with MPM_EVENT?

If I need to use MPM_Event how can I switch to this by default? 

Thanks!

**Comment by AnoopAlias** [comment]
Worker is a safe bet . It forks new process to handle connection. Event use threads .
event is fast because it has no process forking overhead .But historically apache was a forked process and I have seen issues with event on very high load etc. 

As I said worker is a safe bet and always works perfect.Its upto you to use event
