### ISSUE TITLE
ndeploy_backends.service restart/reload isn't triggered

### ISSUE THREAD

**Issue by TaiSHiNet** [AnoopAlias/nDeploy#286]
When a change to a domain is made, ndeploy_backends.service isn't triggered so new PHP values aren't applied (causing domains newly set to use nginx+PHP to fail)

**Comment by AnoopAlias** [comment]
@TaiSHiNet - There is not enough info .Does the php-fpm master process all run?
Is ndeploy_watcher process running? 
What does php-fpm master process log say?
Xtendweb php-fpm system is designed to minimize php-fpm master restarts. So only when a new user is added the php-fpm restart happens.
I am pretty sure this issue is isolated to your machine as I manage servers with over 7k domains running just fine with nginx+php-fpm 
Please open ticket at ops@gnusys.net if you need tech support to assist in this.

**Comment by TaiSHiNet** [comment]
@AnoopAlias ndeploy_watcher.service wasn't running, it was failing (silently) due to existent .pid file
Maybe that was the reason, although maybe ndeploy_watcher.service could handle the pidfile somehow? Just an idea

**Comment by AnoopAlias** [comment]
The watcher crashed. and you will need to manually remove the pid in such cases. This is a rare event, probably something killed the daemon?

**Comment by TaiSHiNet** [comment]
I think it was related to modsecurity imploding my server memory, I'll keep an eye for it

**Comment by AnoopAlias** [comment]
@TaiSHiNet - check SpiderLabs/ModSecurity#1563 . I will incorporate this in the next version of XtendWeb-nginx and hopefully we have the memory issues nailed with that

**Comment by TaiSHiNet** [comment]
Awesome!!! Thanks for the update!
