### ISSUE TITLE
After installing newest RPM and running installation commands as per instructions on wiki all sites are 503 error

### ISSUE THREAD

**Issue by brianjking** [AnoopAlias/nDeploy#44]
@AnoopAlias 

Please help!

**Comment by AnoopAlias** [comment]
If you are proxying ..please see if apache is up

**Comment by brianjking** [comment]
@AnoopAlias 

service httpd status
httpd (pid 1828 1827 1825 1815 1808) is running...

**Comment by brianjking** [comment]
@AnoopAlias Did this version stop allowing me to use PHPBrew versions of PHP?

**Comment by brianjking** [comment]
@AnoopAlias I noticed that inside of /opt/nDeploy/php-fpm.d/ there are only a few sites listed. The sites that are listed here are the ones that are working.

All others are 503 errors.

**Comment by AnoopAlias** [comment]
Please update your ticket at our desk with a domain that isnt working.

**Comment by brianjking** [comment]
@AnoopAlias Done.

**Comment by AnoopAlias** [comment]
@brianjking - Fixed .Was caused due to an instruction in the upgrade process I missed.

If you are using apache+php-fpm you had to run

for CPANELUSER in $(cat /etc/domainusers|cut -d: -f1);do echo "ConfGen:: $CPANELUSER" && /opt/nDeploy/scripts/apache_php_config_generator.py $CPANELUSER;done

too . I will update the instructions
